server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/FirstCrudDatabase
    username: root
    password: shubham@1423

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


